### ISSUE TITLE
Display only on a certain page

### ISSUE THREAD

**Issue by craigwduckett** [refiner-io/js-client-npm#1]
We are trying to implement this in our SaaS app and display the survey in one component only but are having a lot of trouble doing this. Our app is React so we are dynamically loading Refiner using something like

`componentDidMount() {
    _refiner('trackEvent', '');
    _refiner('showForm', '');
}`

and then when the user navigates away we do
`componentWillUnmount() {
    _refiner('hideForm', '');
}`

we have tried a few things to get this to work but to no avail. Do you guys have any recommendations or can you implement something like `_refiner('hideForm', '');` which we can toggle to stop the survey from showing?

Cheers

**Comment by chezmo** [comment]
Hey @craigwduckett ! Sorry for the late reply ... we didn't actively monitor the issues here until now.

We added a method to programmatically hide a survey and also "deactivate" the entire client:
https://refiner.io/docs/kb/install/reference/#close-survey
https://refiner.io/docs/kb/install/reference/#stop-pinging

Hope that helps!
