### ISSUE TITLE
undefined is not an object (evaluating 'e.response.data')

### ISSUE THREAD

**Issue by ipetrovbg** [refiner-io/js-client-npm#2]
Hello,
I've noticed an error has been thrown from the refiner client package. The error happens when for example a device loses connectivity and the ping request fails. As a consequence of that refiner stops showing surveys.

```
{snip} re"),e.response&&400===e.response.status||(g=!0),e.response.data&&e.response.data.ping_again_in?K("refiner_ping_again_after",Math.floor(Date {snip}
 
/*!
* Determine if an object is a Buffer   
*
* @author Feross Aboukhadijeh <https://feross.org>    
* @license MIT
```

**Comment by wallies** [comment]
We recently started seeing this error as well
```
Cannot read property 'data' of undefined

{snip} e"),e.response&&400===e.response.status||(g=!0),e.response.data&&e.response.data.ping_again_in?K("refiner_ping_again_after",Math.floor(Date. {snip}
```
Tends to happen with network connectivity issues, as mentioned above. Is there a way to add retries to the client package?

**Comment by chezmo** [comment]
Hey @ipetrovbg and @wallies ! Thanks for bringing this to our attention and please excuse the late reply. We just saw the issue here.

This should have been fixed a couple of weeks ago. The client should now gracefully handle lost connections.
