### ISSUE TITLE
Refiner injection into the Nuxt

### ISSUE THREAD

**Issue by oscarhandsome** [refiner-io/js-client-npm#4]
Hi, thanks to owners for this package. 

But i can't understand how correctly inject it into config file 

I created file refiner.js into plugins folder, added this file into plugins block in nuxt config file. 
It works, but I see it broke all my app.
Can you give me suggestion how correct inject it? Might be I'm doing incorrect?
![image](https://user-images.githubusercontent.com/8983274/172843854-624101ca-38b3-4a67-a336-2a324f5d5bb6.png)

**nuxt config file:**
```
plugins: [
    { src: '~/plugins/refiner.js', mode: 'client' },
  ],
```

**refiner.js**
```
import Vue from 'vue'
import Refiner from 'refiner-js'

Vue.use(
  Refiner(
    'setProject',
    process.env.REFINER_ID || '00000000-my-id-000000000'
  )
  //   Refiner('identifyUser', {
  //     id: 'USER-ID-ABC-123', // Each user needs an ID or email address
  //     email: 'jane@awesome.com', // Each user needs an ID or email address
  //     name: 'Jane Doe', // The full name of the user
  //   })
)
```

I also have another implementation based on [this answer.](https://stackoverflow.com/questions/64233657/include-a-custom-script-in-the-head-tag-in-nuxt). But I want to do the same way as all other plugins. Also I need get and update user info if user logged in.

upd:
`import { _refiner as Refiner } from 'refiner-js'`
works I suggest

**Comment by oscarhandsome** [comment]
created this solution:

```
import _refiner from 'refiner-js'

_refiner('setProject', '4e84dab0-my-own-ID-930deab8d014')

const random = Math.random()
let user = {
  id: 'USER-ID-ABC-' + random,
  email: 'anonymous-' + random + '@gmail.com',
  name: 'anonymous-' + random,
}

export default ({ store }) => {
  if (store.state.auth.loggedIn) {
    user = {
      id: store.state.auth.user.user_id,
      email: store.state.auth.user.email,
      name:
        store.state.auth.user.first_name +
        ' ' +
        store.state.auth.user.last_name,
    }
  }

  _refiner('identifyUser', user)
}
```

**Comment by chezmo** [comment]
Thanks a lot for providing your solution Oscar. Closing this issue now.
