### ISSUE TITLE
No .d.ts file for typescript

### ISSUE THREAD

**Issue by chezmo** [refiner-io/js-client-npm#5]

**Comment by chezmo** [comment]
When using typescript, there is no .d.ts type file present anywhere. Adding one would be helpful for other developers.

**Comment by Waterstraal** [comment]
Would be really helpful indeed to have types provided.

**Comment by bed-sb** [comment]
not having type script types in 2023 is pretty poor form ;)

**Comment by chezmo** [comment]
Thanks a lot for your patience @Waterstraal and @bed-sb. We've just pushed a new version that contains a .d.ts file.
